# Maximum duration of CI workflows before they are considered timed out.
# (Required)
timeout = 3600

# Labels that should be set on a PR after an event happens.
# "+<label>" adds the label, while "-<label>" removes the label after the event.
# Supported events:
# - try: Try build has started
# - try_succeed: Try build has finished
# - try_failed: Try build has failed
# - auto: Auto build has started
# - auto_succeed: Auto build has finished
# - auto_failed: Auto build has failed
# (Optional)
[labels]
approve = ["+approved"]
try = ["+foo", "-bar"]
try_succeed = ["+foobar", "+foo", "+baz"]
try_failed = []
auto = ["+merge-testing"]
auto_succeed = ["+merged", "-merge-testing"]
auto_failed = ["+merge-failed", "-merge-testing"]
